version: "3.9"
services:
  drone:
    build:
      context: .
      dockerfile: drone/Dockerfile
    volumes:
      - ./sample-config:/etc/spawner
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      /etc/spawner/drone.toml

  controller:
    build:
      context: .
      dockerfile: controller/Dockerfile
    volumes:
      - ./sample-config:/etc/spawner
    command:
      /etc/spawner/controller.toml

  nats:
    image: nats:latest
    command:
      - "--jetstream"
      - "--auth=my-secret-token"
