version: "3.9"
services:
  drone:
    build:
      context: .
      dockerfile: drone/Dockerfile
    # image: ghcr.io/drifting-in-space/spawner-drone:sha-19997e7
    volumes:
      - ./sample-config:/etc/spawner:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      /etc/spawner/drone.toml

  controller:
    build:
      context: .
      dockerfile: controller/Dockerfile
    # image: ghcr.io/drifting-in-space/spawner-controller:sha-19997e7
    volumes:
      - ./sample-config:/etc/spawner:ro
    command:
      /etc/spawner/controller.toml

  nats:
    image: nats:latest
    command:
      "--jetstream"
    ports:
      - "127.0.0.1:4222:4222"

  ip-api:
    image: ghcr.io/drifting-in-space/ip-api:latest

  firefox:
    build:
      context: sample-config/firefox
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
