[package]
name = "dis-spawner-controller"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.62"
chrono = "0.4.22"
clap = { version = "3.2.17", features = ["derive"] }
dashmap = "5.3.4"
dis-spawner = {path = "../core"}
rand = "0.8.5"
tokio = { version = "1.20.1", features = ["macros", "rt"] }
tracing = "0.1.36"

[[bin]]
name = "spawner-controller"
path = "src/main.rs"
